---
title: "Ársreikningar Sveitarfélaga"
author: 
    -   name: "Brynjólfur Gauti Guðrúnar Jónsson"
        url: "https://twitter.com/bgautijonsson"
        affiliation: "Tölfræði, Raunvísindadeild Háskóla Íslands"
        affiliation-url: "https://www.hi.is/tolfraedi_0"
date: today
format: 
    html:
        code-fold: true
        toc: true
        toc-location: right
        toc-title: Efnisyfirlit
editor: source
theme: flatly
title-block-banner: true
standalone: true
self-contained: true
---


```{r}
#| include: false

library(cowplot)
library(tidyverse)
library(scales)
library(pxweb)
library(ggthemes)
library(kableExtra)
library(gganimate)
library(lubridate)
library(geomtextpath)
library(ggtext)
library(here)
library(readxl)
library(janitor)
```

```{r}
d_21 <- read_csv2("uppg202112island.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(tegund2 == "Launakostnaður") |> 
    group_by(samtala0, samtala1, samtala2, samtala3, ar, arsfjordungur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    arrange(desc(raun))


d_20 <- read_csv2("uppg202012island.csv") |> 
    filter(tegund2 == "Launakostnaður") |> 
    group_by(samtala0, samtala1, samtala2, samtala3, ar, arsfjordungur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    arrange(desc(raun))


d_19 <- read_csv2("uppgj201912island.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(tegund2 == "Launakostnaður") |> 
    group_by(samtala0, samtala1, samtala2, samtala3, ar, arsfjordungur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    arrange(desc(raun))

d_18 <- read_csv2("uppg201812island.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(tegund0 == "Laun og launatengd gjöld") |> 
    group_by(samtala0, samtala1, samtala2, samtala3, ar, arsfjordungur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    arrange(desc(raun))

d_17 <- read_csv2("rvk201712.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(xtgr1 == "Launakostnaður") |> 
    mutate(xeining4 = ifelse(xeining5 == "Velferðarsvið", xþjon1, xeining4),
           xeining3 = ifelse(xeining5 == "Velferðarsvið", xþjon2, xeining3),
           xeining2 = ifelse(xeining5 == "Velferðarsvið", xþjon3, xeining2)) |> 
    group_by(samtala1 = xeining5, samtala2 = xeining4, samtala3 = xeining3, samtala0 = xeining1, samtala4 = xeining2,
             ar, arsfjordungur = ar_fjordungur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |>  
    arrange(desc(raun))


d_16 <- read_csv2("rvk2016.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(XTGR1 == "Launakostnaður") |> 
    mutate(XEINING4 = ifelse(XEINING5 == "Velferðarsvið", XÞJON1, XEINING4),
           XEINING3 = ifelse(XEINING5 == "Velferðarsvið", XÞJON2, XEINING3),
           XEINING2 = ifelse(XEINING5 == "Velferðarsvið", XÞJON3, XEINING2)) |> 
    group_by(samtala1 = XEINING5, samtala2 = XEINING4, samtala3 = XEINING3, samtala0 = XEINING1, samtala4 = XEINING2,
             ar = AR, arsfjordungur = AR_FJORDUNGUR) |> 
    summarise(raun = sum(RAUN),
              .groups = "drop") |> 
    arrange(desc(raun))


d_15 <- read_csv2("rvk2015.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(XTGR1 == "Launakostnaður") |> 
    mutate(XEINING4 = ifelse(XEINING5 == "Velferðarsvið", XÞJON1, XEINING4),
           XEINING3 = ifelse(XEINING5 == "Velferðarsvið", XÞJON2, XEINING3),
           XEINING2 = ifelse(XEINING5 == "Velferðarsvið", XÞJON3, XEINING2)) |> 
    group_by(samtala1 = XEINING5, samtala2 = XEINING4, samtala3 = XEINING3, samtala0 = XEINING1, samtala4 = XEINING2,
             ar = AR, arsfjordungur = AR_FJORDUNGUR) |> 
    summarise(raun = sum(RAUN),
              .groups = "drop") |>
    arrange(desc(raun))

d_14 <- read_csv2("rvk2014.csv", locale = locale(encoding = "ISO-8859-1")) |> 
    filter(XTGR1 == "Launakostnaður") |> 
    mutate(XEINING4 = ifelse(XEINING5 == "Velferðarsvið", XÞJON1, XEINING4),
           XEINING3 = ifelse(XEINING5 == "Velferðarsvið", XÞJON2, XEINING3),
           XEINING2 = ifelse(XEINING5 == "Velferðarsvið", XÞJON3, XEINING2)) |> 
    group_by(samtala1 = XEINING5, samtala2 = XEINING4, samtala3 = XEINING3, samtala0 = XEINING1, samtala4 = XEINING2,
             ar = AR, arsfjordungur = AR_FJORDUNGUR) |> 
    summarise(raun = sum(RAUN),
              .groups = "drop") |>
    arrange(desc(raun))





```

# Aftur til 2018

```{r}
d <- d_21 |> 
    bind_rows(
        d_20,
        d_19,
        d_18
    ) |> 
    ungroup() |> 
    mutate(dags = ymd(str_c(ar, c("01", "04", "07", "10")[arsfjordungur], "-01")))
```


## Yfirsvið

```{r}
words <- c("skrifstof", "stjórn", "mannauð", "ráð", "upplýsingatækni", "gagna")
words_pattern <- str_c(words, collapse = "|")

d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala2),  "barnavernd") ~ "Annað",
                               str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               TRUE ~ "Annað")) |> 
    filter(flokkur == "Annað") |> 
    group_by(samtala3, flokkur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |>
    arrange(desc(raun)) |> 
    mutate(p = raun / sum(raun),
           cum_p = cumsum(p))

```


upplýsingatækni, nefndir og ráð

```{r}
d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    distinct(flokkur, samtala3) |> 
    arrange(flokkur)
```

```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = 2018:2021, limits = c(2017.9, 2021.1)) +
    scale_y_continuous(labels = label_percent(), limits = c(0, 0.2), expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_half_open() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð', 'ráð' og 'upplýsingatækni' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "yfirsvid.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```





## Skóla- og frístundasvið


```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    filter(samtala1 == "Skóla- og frístundasvið") |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = 2018:2021, limits = c(2017.9, 2021.1)) +
    scale_y_continuous(labels = label_percent(), limits = c(0, 0.1), expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_half_open() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Skóla- og frístundasviðs Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð' og 'ráðgj' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "skola_og_fristundasvid.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```




## Velferðarsvið

```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    filter(samtala1 == "Velferðarsvið") |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = 2018:2021, limits = c(2017.9, 2021.1)) +
    scale_y_continuous(labels = label_percent(), limits = c(0, 0.25), expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_half_open() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Velferðarsviðs Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð' og 'ráðgj' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "velferdarsvid.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```


# Aftur til 2014

```{r}
d <- d_21 |> 
    bind_rows(
        d_20,
        d_19,
        d_18,
        d_17,
        d_16,
        d_15,
        d_14
    ) |> 
    ungroup() |> 
    mutate(dags = ymd(str_c(ar, c("01", "04", "07", "10")[arsfjordungur], "-01")))
```

## Yfirsvið

```{r}
words <- c("skrifstof", "stjórn", "mannauð", "ráð", "upplýsingatækni", "gagna")
words_pattern <- str_c(words, collapse = "|")

d |> 
    filter(ar < 2018, samtala1 == "Velferðarsvið") |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala4), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    filter(flokkur == "Annað") |> 
    group_by(samtala1, samtala2, samtala3, samtala0, flokkur) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |>
    arrange(desc(raun)) |> 
    mutate(p = raun / sum(raun),
           cum_p = cumsum(p))

```



```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
words <- c("skrifstof", "stjórn", "mannauð", "ráð", "upplýsingatækni", "gagna")
words_pattern <- str_c(words, collapse = "|")

plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    geom_rangeframe() +
    scale_x_continuous(breaks = 2014:2021, limits = c(2013.95, 2021.05)) +
    scale_y_continuous(labels = label_percent(), 
                       limits = c(0, 0.2), 
                       breaks = c(range(plot_dat$hlutf), 0, 0.2)),
                       expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_tufte() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð', 'ráð', 'gagna' og 'upplýsingatækni' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "yfirsvid_2014.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```



```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0),  "barnavernd") ~ "Annað",
                               str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, samtala3, samtala0, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    filter(flokkur != "Annað") |> 
    arrange(desc(ar), desc(hlutf)) |> 
    group_by(ar) |> 
    top_n(2, wt = hlutf)

```



## Skóla- og frístundasvið


```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    filter(samtala1 == "Skóla- og frístundasvið") |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = 2014:2021, limits = c(2013.9, 2021.1)) +
    scale_y_continuous(labels = label_percent(), limits = c(0, 0.1), expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_half_open() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Skóla- og frístundasviðs Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð', 'ráð', 'gagna' og 'upplýsingatækni' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "skola_og_fristundasvid_2014.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```




## Velferðarsvið

```{r, fig.width = 12, fig.asp = 0.5, out.width = "100%"}
plot_dat <- d |> 
    mutate(flokkur = case_when(str_detect(str_to_lower(samtala0), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala2), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala1), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               str_detect(str_to_lower(samtala3), words_pattern) ~ "Skrifstofur, stjórnir og þess háttar", 
                               
                               TRUE ~ "Annað")) |> 
    group_by(flokkur, ar) |> 
    filter(samtala1 == "Velferðarsvið") |> 
    group_by(flokkur, ar) |> 
    summarise(raun = sum(raun),
              .groups = "drop") |> 
    group_by(ar) |> 
    mutate(hlutf = raun / sum(raun)) |> 
    ungroup() |> 
    mutate(x = ar,
           y = hlutf,
           label = flokkur) |> 
    filter(flokkur != "Annað")


p <- plot_dat |> 
    ggplot(aes(ar, hlutf)) +
    geom_line() +
    geom_point() +
    scale_x_continuous(breaks = 2014:2021, limits = c(2013.9, 2021.1)) +
    scale_y_continuous(labels = label_percent(), limits = c(0, 0.25), expand = expansion()) +
    scale_colour_brewer(type = "qual", palette = "Set1") +
    coord_cartesian(expand = F) +
    theme_half_open() +
    theme(legend.position = "none",
          plot.margin = margin(t = 5, r = 15, b = 5, l = 5)) +
    labs(x = NULL, y = NULL, fill = NULL,
         title = "Hlutfall launa og launatengra útgjalda Velferðarsviðs Reykjavíkurborgar sem fara í skrifstofustörf osf",
         subtitle = "Útgjöld flokkuð með því að leita að 'skrifstof', 'stjórn', 'mannauð' og 'ráðgj' í öllum liðum opins bókhalds Reykjavíkurborgar",
         caption = "Kóði og gögn: https://github.com/bgautijonsson/bokhald_rvk")

p

ggsave(plot = p, filename = "velferdarsvid.png",
       width = 8, height = 0.5 * 8, scale = 1.3, bg = "white")
```